structure(
  list(
    method = "GET",
    url = "https://api.coinbase.com/api/v3/brokerage/market/products/BTC-USD",
    status_code = 200L,
    headers = structure(
      list(date = "Thu, 19 Jun 2025 19:38:14 GMT",
           `content-type` = "application/json; charset=utf-8",
           `access-control-allow-headers` = "Authorization, Content-Type, Accept, Second-Factor-Proof-Token, Client-Id, Access-Token, X-Cb-Project-Name, X-Cb-Is-Logged-In, X-Cb-Platform, X-Cb-Session-Uuid, X-Cb-Pagekey, X-Cb-UJS, Fingerprint-Tokens, X-Cb-Device-Id, X-Cb-Version-Name,Content-Type, Accept, Second-Factor-Proof-Token, Client-Id, Access-Token, X-Cb-Project-Name, X-Cb-Is-Logged-In, X-Cb-Platform, X-Cb-Session-Uuid, X-Cb-Pagekey, X-Cb-Ujs, Fingerprint-Tokens, X-Cb-Device-Id, X-Cb-Version-Name",
           `access-control-allow-methods` = "GET,POST,DELETE,PUT,GET,POST,DELETE,PUT,PATCH",
           `access-control-allow-private-network` = "true,true",
           `access-control-expose-headers` = "",
           `access-control-max-age` = "7200,7200",
           `cache-control` = "public, max-age=14400",
           `strict-transport-security` = "max-age=31536000; includeSubDomains; preload",
           `trace-id` = "REDACTED",
           vary = "Origin,Origin, Accept-Encoding",
           `x-content-type-options` = "nosniff",
           `x-dns-prefetch-control` = "off",
           `x-download-options` = "noopen",
           `x-frame-options` = "SAMEORIGIN",
           `x-xss-protection` = "1; mode=block",
           `last-modified` = "Thu, 19 Jun 2025 19:38:13 GMT",
           `cf-cache-status` = "HIT",
           expires = "Thu, 19 Jun 2025 23:38:14 GMT",
           `report-to` = "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=tdrw7Yd3yBQfGiBzbtGGBdOUTFV8LHWvxDpuaY7KAvrEud2mQ2JWhVuvhag4PnV2tOoZxcab%2BFcOoWGlePny%2BwGuqzA6sm7qHPt0fwRFS2f%2Bc%2B%2BfGcB%2FYoZSUcOq5mgJ1Cg%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
           nel = "{\"success_fraction\":0.01,\"report_to\":\"cf-nel\",\"max_age\":604800}",
           `set-cookie` = "REDACTED",
           server = "cloudflare",
           `cf-ray` = "95257c4ddfe50144-MAD",
           `content-encoding` = "gzip"),
      redact = character(0),
      class = "httr2_headers"),
    body = charToRaw("{\"product_id\":\"BTC-USD\",\"price\":\"104263.17\",\"price_percentage_change_24h\":\"0.08036133805659\",\"volume_24h\":\"3148.76940085\",\"volume_percentage_change_24h\":\"-36.62922117814779\",\"base_increment\":\"0.00000001\",\"quote_increment\":\"0.01\",\"quote_min_size\":\"1\",\"quote_max_size\":\"150000000\",\"base_min_size\":\"0.00000001\",\"base_max_size\":\"3400\",\"base_name\":\"Bitcoin\",\"quote_name\":\"US Dollar\",\"watched\":false,\"is_disabled\":false,\"new\":false,\"status\":\"online\",\"cancel_only\":false,\"limit_only\":false,\"post_only\":false,\"trading_disabled\":false,\"auction_mode\":false,\"product_type\":\"SPOT\",\"quote_currency_id\":\"USD\",\"base_currency_id\":\"BTC\",\"fcm_trading_session_details\":null,\"mid_market_price\":\"\",\"alias\":\"\",\"alias_to\":[\"BTC-USDC\"],\"base_display_symbol\":\"BTC\",\"quote_display_symbol\":\"USD\",\"view_only\":false,\"price_increment\":\"0.01\",\"display_name\":\"BTC-USD\",\"product_venue\":\"CBE\",\"approximate_quote_24h_volume\":\"328300679.33\",\"new_at\":\"2023-01-01T00:00:00Z\"}"),
    cache = new.env(parent = emptyenv())),
  class = "httr2_response")
