structure(
  list(
    method = "GET",
    url = "https://api.coinbase.com/api/v3/brokerage/market/product_book?product_id=BTC-USD&limit=1",
    status_code = 200L,
    headers = structure(
      list(date = "Thu, 19 Jun 2025 19:37:43 GMT",
           `content-type` = "application/json; charset=utf-8",
           `access-control-allow-headers` = "Authorization, Content-Type, Accept, Second-Factor-Proof-Token, Client-Id, Access-Token, X-Cb-Project-Name, X-Cb-Is-Logged-In, X-Cb-Platform, X-Cb-Session-Uuid, X-Cb-Pagekey, X-Cb-UJS, Fingerprint-Tokens, X-Cb-Device-Id, X-Cb-Version-Name,Content-Type, Accept, Second-Factor-Proof-Token, Client-Id, Access-Token, X-Cb-Project-Name, X-Cb-Is-Logged-In, X-Cb-Platform, X-Cb-Session-Uuid, X-Cb-Pagekey, X-Cb-Ujs, Fingerprint-Tokens, X-Cb-Device-Id, X-Cb-Version-Name",
           `access-control-allow-methods` = "GET,POST,DELETE,PUT,GET,POST,DELETE,PUT,PATCH",
           `access-control-allow-private-network` = "true,true",
           `access-control-expose-headers` = "",
           `access-control-max-age` = "7200,7200",
           `cache-control` = "public, max-age=14400",
           `strict-transport-security` = "max-age=31536000; includeSubDomains; preload",
           `trace-id` = "REDACTED",
           vary = "Origin,Origin, Accept-Encoding",
           `x-content-type-options` = "nosniff",
           `x-dns-prefetch-control` = "off",
           `x-download-options` = "noopen",
           `x-frame-options` = "SAMEORIGIN",
           `x-xss-protection` = "1; mode=block",
           `last-modified` = "Thu, 19 Jun 2025 19:37:43 GMT",
           `cf-cache-status` = "EXPIRED",
           expires = "Thu, 19 Jun 2025 23:37:43 GMT",
           `report-to` = "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=7Nxu7UaREofoz5YOXwo7rEi1idApMnnz9iozD%2Fva%2Fb%2BPGgUeF8GFeU21Mphd7%2BrtzLzR4mmb3oUuOw1V1rDqlNEFPU4zk8xYiXjWlezIH%2B0Jq0fmL3nxSneA%2BqjBQtCXTYg%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
           nel = "{\"success_fraction\":0.01,\"report_to\":\"cf-nel\",\"max_age\":604800}",
           `set-cookie` = "REDACTED",
           server = "cloudflare",
           `cf-ray` = "95257b8ae8c90144-MAD",
           `content-encoding` = "gzip"),
      redact = character(0),
      class = "httr2_headers"),
    body = charToRaw("{\"pricebook\":{\"product_id\":\"BTC-USD\",\"bids\":[{\"price\":\"104262.57\",\"size\":\"0.04846832\"}],\"asks\":[{\"price\":\"104262.58\",\"size\":\"0.01967579\"}],\"time\":\"2025-06-19T19:37:43.116988Z\"},\"last\":\"104262.575\",\"mid_market\":\"104262.575\",\"spread_bps\":\"0.000959116876\",\"spread_absolute\":\"0.01\"}"),
    cache = new.env(parent = emptyenv())),
  class = "httr2_response")
